envVariables:
  ServiceSettings__MessageBroker: SERVICEBUS
  ServiceSettings__KeyVaultName: dotnetplayeconomy
  SeqSettings__Host: seq.observability
  SeqSettings__Port: 5341

resources:
  limits:
    memory: "128Mi"
    cpu: "150m"

container:
  liveness:
    path: /health/live
    initialDelaySeconds: 30
  readiness:
    path: /health/ready
    initialDelaySeconds: 30

service:
  type: ClusterIP
  port: 80
